### ISSUE TITLE
Output is empty in Win8.x

### ISSUE THREAD

**Issue by laszlogal** [ryoyakawai/WebMIDIAPIWrapper#3]
Hello,
I am trying the Live Demo on Widows 8.0 and Windows 8.1 with Chrome 43 (jazz plugin also installed btw), but Output select is empty, no Microsoft GS Wavetable synth or such. Midi is allowed for that page. It works perfectly on mac. What should I do? Thanks

**Comment by ryoyakawai** [comment]
Thank you for using the wrapper.
Regarding "Microsoft GS Wavetable synth":
There are discussion at chromium ML about how to safely handle software synth. And it is true that "Microsoft GS Wavetable synth" does not appear in MIDI output list even if you write from the scratch without any wrappers or libraries.

One question.
Is it also impossible to get physical connected synth in the MIDI output list? 
If the answer is true, this wrapper has some bugs.

**Comment by laszlogal** [comment]
Thank you for the quick answer. On mac the IAC driver appears, so wrapper is working, I was just wondering if I do wrong something, or is it a bug on windows.
We use the wrapper to implement midi features to GeoGebra Web version, and it's pretty cool, but using default soft synth would be  mandatory in our case. Thanks again. Laszlo

**Comment by ryoyakawai** [comment]
Cool!

*default soft synth would be mandatory*
Have you ever heard of Web MIDI Link??
Web MIDI Link itself is just a kind of protocol, but it allow any web applications to play song without hardware synth and software synth, because this protocol send MIDI message(as json format) against the synth made by web audio api. 
http://www.g200kg.com/en/docs/webmidilink/

If you would like to try, just use this application with standard MIDI file.
https://ryoyakawai.github.io/smfplayer/
(note that: please use "SoundFont: Yamaha XG".)

Thanks!

**Comment by laszlogal** [comment]
Thanks, we will try it! Actually we liked to avoid using external SoundFonts to save space, but maybe we cannot.
